application: societycase
version: 1
runtime: python
api_version: 1


builtins:
- datastore_admin: on
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /insertgraph/.*
  script: insertgraph.py
  login: admin

- url: /register/.*
  script: registeruser.py
  login: admin

- url: /.*
  script: main.py
  login: required
